apiVersion: apps/v1
kind: Deployment
metadata:
  name: coursework
  labels:
    app: coursework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coursework
  template:
    metadata:
      labels:
        app: coursework
    spec:
      containers:
        - name: coursework
          image: giantconiku/coursework-devops:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: logs-volume
              mountPath: /var/logs
      volumes:
        - name: logs-volume
          persistentVolumeClaim:
            claimName: logs-pvc