apiVersion: v1
kind: Service
metadata:
  name: coursework-svc1
spec:
  selector:
    app: coursework
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: coursework-svc2
spec:
  selector:
    app: coursework
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8080
  type: NodePort